theme: jekyll-theme-cayman
title: Leon's homepage
description: My writing on AI/ML, Programming, and Home Renovation 
url: "https://leonletto.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
